#pragma once

#define RBL_MOUSE_BUTTON_1         0
#define RBL_MOUSE_BUTTON_2         1
#define RBL_MOUSE_BUTTON_3         2
#define RBL_MOUSE_BUTTON_4         3
#define RBL_MOUSE_BUTTON_5         4
#define RBL_MOUSE_BUTTON_6         5
#define RBL_MOUSE_BUTTON_7         6
#define RBL_MOUSE_BUTTON_8         7
#define RBL_MOUSE_BUTTON_LAST      RBL_MOUSE_BUTTON_8
#define RBL_MOUSE_BUTTON_LEFT      RBL_MOUSE_BUTTON_1
#define RBL_MOUSE_BUTTON_RIGHT     RBL_MOUSE_BUTTON_2
#define RBL_MOUSE_BUTTON_MIDDLE    RBL_MOUSE_BUTTON_3